version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
    expose:
      - 8000
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend